# /* vim: set filetype=dockerfile : */

FROM vimrobotframework/vim_base:latest
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

RUN sudo python3 -m pip install --upgrade pip
RUN sudo python3 -m pip install robotframework-lint robotframework-requests
RUN sudo apt install universal-ctags -y

COPY ./robot/1exec_tests.robot robot/1exec_tests.robot
COPY ./robot/2exec_tests.robot robot/2exec_tests.robot
COPY ./robot/test.robot robot/test.robot
RUN sudo chown ${USER}: robot

RUN git clone https://github.com/junegunn/vader.vim.git .vim/pack/plugins/start/vader.vim

RUN mkdir -p .vim/pack/plugins/start/vim_robotframework/plugin
RUN mkdir -p .vim/pack/plugins/start/vim_robotframework/syntax
RUN mkdir -p .vim/pack/plugins/start/vim_robotframework/ftdetect

COPY ./test test
COPY ./start_vader.bash start_vader.bash

COPY ./vim/vimrc .vimrc
COPY ./vim/robot-ftdetect.vim .vim/pack/plugins/start/vim_robotframework/ftdetect/robot.vim
COPY ./vim/robot-syntax.vim .vim/pack/plugins/start/vim_robotframework/syntax/robot.vim
COPY ./vim/list_tests.py .vim/pack/plugins/start/vim_robotframework/ftplugin/list_tests.py
COPY ./vim/robot-commands.vim .vim/pack/plugins/start/vim_robotframework/ftplugin/robot.vim

COPY ./vim/rflint.txt .vim/pack/plugins/start/vim_robotframework/doc/robot.txt
COPY ./vim/tags .vim/pack/plugins/start/vim_robotframework/doc/tags
