# /* vim: set filetype=dockerfile : */

FROM vimrobotframework/vim_base:latest
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

# Install necessary tools
RUN sudo apt-get update && sudo apt-get install -y git universal-ctags

# Install necessary Vim plugins
RUN git clone https://github.com/preservim/tagbar.git .vim/pack/plugins/start/tagbar
RUN git clone --depth 1 https://github.com/dense-analysis/ale.git .vim/pack/plugins/start/ale

# Install robot framework tools
RUN sudo python3 -m pip install --upgrade pip && sudo python3 -m pip install robotframework-lint robotframework-requests

# Clean tools which will be needed no more
RUN sudo apt-get remove -y git

# Add custom linting bridge between ale and rflint 
RUN mkdir -p .vim/pack/plugins/start/ale/ale_linters/robot
COPY other/rflint.vim .vim/pack/plugins/start/ale/ale_linters/robot/rflint.vim

# Copy folder with example robot framework code
COPY other/robot robot

# Change privilages, so USER can user and edit them
RUN sudo chown ${USER}: robot

# Install vim_robotframework plugin
COPY .vimrc .vimrc
COPY ftdetect .vim/pack/plugins/start/vim_robotframework/ftdetect
COPY syntax .vim/pack/plugins/start/vim_robotframework/syntax
COPY plugin .vim/pack/plugins/start/vim_robotframework/plugin
COPY doc .vim/pack/plugins/start/vim_robotframework/doc

# Generate tags for doc files, so user can use them out of the box
RUN sudo vim -c 'helptags .vim/pack/plugins/start/vim_robotframework/doc' -c 'q'
