# /* vim: set filetype=dockerfile : */

FROM vimrobotframework/vim_base:latest
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

RUN sudo apt-get install -y git
RUN git clone https://github.com/junegunn/vader.vim.git .vim/pack/plugins/start/vader.vim

COPY other/start_vader.bash start_vader.bash
COPY other/test test
COPY syntax .vim/syntax
COPY ftdetect .vim/ftdetect
COPY autoload .vim/autoload
COPY ftplugin .vim/ftplugin
