# /* vim: set filetype=dockerfile : */

FROM vimrobotframework/vim_base_syntax_test:latest
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

RUN sudo apt update
RUN sudo apt install universal-ctags -y
RUN git clone https://github.com/preservim/tagbar.git .vim/pack/plugins/start/tagbar
RUN git clone --depth 1 https://github.com/dense-analysis/ale.git .vim/pack/plugins/start/ale
RUN sudo python3 -m pip install --upgrade pip
RUN sudo python3 -m pip install robotframework-lint robotframework-requests

# COPY code/robot robot
# COPY code/vim vim
COPY ./robot/1exec_tests.robot robot/1exec_tests.robot
COPY ./robot/2exec_tests.robot robot/2exec_tests.robot
COPY ./robot/add_client_owners.robot robot/add_client_owners.robot
RUN sudo chown ${USER}: robot

RUN mkdir -p .vim/pack/plugins/start/ale/ale_linters/robot
COPY ./vim/rflint.vim .vim/pack/plugins/start/ale/ale_linters/robot/rflint.vim

RUN mkdir -p .vim/pack/plugins/start/vim_robotframework/plugin
RUN mkdir -p .vim/pack/plugins/start/vim_robotframework/syntax
RUN mkdir -p .vim/pack/plugins/start/vim_robotframework/ftdetect
COPY ./vim/vimrc .vimrc
COPY ./vim/robot-ftdetect.vim .vim/pack/plugins/start/vim_robotframework/ftdetect/robot.vim
COPY ./vim/robot-syntax.vim .vim/pack/plugins/start/vim_robotframework/syntax/robot.vim
COPY ./vim/list_tests.py .vim/pack/plugins/start/vim_robotframework/plugin/list_tests.py
COPY ./vim/robot-commands.vim .vim/pack/plugins/start/vim_robotframework/plugin/robot-commands.vim

RUN testing.vim/tvim test plugin/robot_test.vim
RUN rm -rf plugin
RUN rm -rf testing.vim
RUN rm .vim/syntax/robot.vim
RUN rm .vim/ftdetect/robot.vim
