# /* vim: set filetype=dockerfile : */

FROM python:3.8-slim-buster
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

RUN apt-get update && apt-get install -y git build-essential libncurses5-dev libncursesw5-dev

RUN rm -rf /tmp/vim
RUN git clone https://github.com/vim/vim.git /tmp/vim
RUN make -C /tmp/vim
RUN make install -C /tmp/vim
RUN rm -rf /tmp/vim
