# /* vim: set filetype=dockerfile : */

FROM vimrobotframework/vim_base:latest
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

ENV TEST_VIM="/usr/local/bin/vim"
RUN git clone -q --depth 1 https://github.com/arp242/testing.vim.git ${USER_HOME}/testing.vim

RUN mkdir plugin
COPY code/robot ./plugin
COPY code/vim ./vim

RUN cp vim/vimrc ${USER_HOME}/.vimrc
RUN cp vim/robot-syntax.vim ${USER_HOME}/.vim/syntax/robot.vim
RUN cp vim/robot-ftdetect.vim ${USER_HOME}/.vim/ftdetect/robot.vim

RUN ${USER_HOME}/testing.vim/tvim gen-syn plugin/add_client_owners.robot > plugin/robot_test.vim
