# /* vim: set filetype=dockerfile : */

FROM vimrobotframework/vim_base:latest
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

RUN sudo apt update
RUN sudo apt install universal-ctags -y
RUN git clone https://github.com/preservim/tagbar.git .vim/pack/plugins/start/tagbar
RUN git clone --depth 1 https://github.com/dense-analysis/ale.git .vim/pack/plugins/start/ale
RUN sudo python3 -m pip install --upgrade pip
RUN sudo python3 -m pip install robotframework-lint robotframework-requests

COPY code/robot/1exec_tests.robot robot/1exec_tests.robot
COPY code/robot/2exec_tests.robot robot/2exec_tests.robot
RUN sudo chown ${USER}: robot

RUN mkdir -p .vim/pack/plugins/start/ale/ale_linters/robot
COPY code/vim/rflint.vim .vim/pack/plugins/start/ale/ale_linters/robot/rflint.vim

RUN mkdir -p .vim/pack/plugins/start/vim_robotframework/plugin
RUN mkdir -p .vim/pack/plugins/start/vim_robotframework/syntax
RUN mkdir -p .vim/pack/plugins/start/vim_robotframework/ftdetect

COPY code/vim/vimrc .vimrc
COPY code/vim/robot-ftdetect.vim .vim/pack/plugins/start/vim_robotframework/ftdetect/robot.vim
COPY code/vim/robot-syntax.vim .vim/pack/plugins/start/vim_robotframework/syntax/robot.vim
COPY code/vim/list_tests.py .vim/pack/plugins/start/vim_robotframework/plugin/list_tests.py
COPY code/vim/robot-commands.vim .vim/pack/plugins/start/vim_robotframework/plugin/robot-commands.vim
