# /* vim: set filetype=dockerfile : */

FROM vimrobotframework/vim_base:latest
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

USER root

RUN git clone --depth 1 https://github.com/dense-analysis/ale.git ${USER_HOME}/.vim/pack/plugins/start/ale
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install robotframework-lint robotframework-requests

WORKDIR ${USER_HOME}/vim_robotframework
COPY ./robot .
COPY ./vim .

RUN cp ./vimrc-ale ${USER_HOME}/.vimrc
RUN cp ./robot-syntax.vim ${USER_HOME}/.vim/syntax/robot.vim
RUN cp ./robot-ftdetect.vim ${USER_HOME}/.vim/ftdetect/robot.vim

RUN mkdir -p ${USER_HOME}/.vim/pack/plugins/start/ale/ale_linters/robot
RUN cp ./rflint.vim ${USER_HOME}/.vim/pack/plugins/start/ale/ale_linters/robot/rflint.vim

USER ${USER}
