# /* vim: set filetype=dockerfile : */

FROM vimrobotframework/vim_base:latest
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

RUN git clone -q --depth 1 https://github.com/arp242/testing.vim.git testing.vim

COPY code/robot plugin
COPY code/vim vim

RUN sudo chown ${USER}: vim
RUN sudo chown ${USER}: plugin
RUN cp vim/vimrc .vimrc
RUN cp vim/robot-syntax.vim .vim/syntax/robot.vim
RUN cp vim/robot-ftdetect.vim .vim/ftdetect/robot.vim

RUN testing.vim/tvim gen-syn plugin/add_client_owners.robot > plugin/robot_test.vim
