# /* vim: set filetype=dockerfile : */

FROM python:3.8-slim-buster
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

RUN apt-get update && apt-get install -y git build-essential libncurses5-dev libncursesw5-dev sudo

# Compile Vim
RUN git clone https://github.com/vim/vim.git /tmp/vim
RUN make -C /tmp/vim
RUN make install -C /tmp/vim

# Clean
RUN rm -rf /tmp/vim

# Create user
ARG USER=vim_robotframework
ENV USER ${USER}
RUN adduser ${USER} \
      && echo "${USER}   ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

ENV USER_HOME /home/${USER}
RUN chown -R ${USER}:${USER} ${USER_HOME}

USER ${USER}
WORKDIR ${USER_HOME}

# Create vim folders for packages
RUN mkdir -p .vim/pack/plugins/start
RUN mkdir .vim/syntax
RUN mkdir .vim/ftdetect
