# /* vim: set filetype=dockerfile : */

FROM my-vim:latest
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

RUN apt-get update && apt-get install -y git sudo

RUN useradd -ms /bin/bash MyUser
RUN echo 'MyUser:test' | chpasswd 
RUN echo 'MyUser ALL=(ALL:ALL) ALL' >> /etc/sudoers

RUN mkdir -p /home/MyUser/.vim/pack/plugins/start

RUN mkdir /home/MyUser/.vim/syntax
RUN mkdir /home/MyUser/.vim/ftdetect

COPY ./vim /home/MyUser/vim-rf
COPY ./robot /home/MyUser/vim-rf
RUN cp /home/MyUser/vim-rf/vimrc /home/MyUser/.vimrc

RUN cp /home/MyUser/vim-rf/robot-syntax.vim /home/MyUser/.vim/syntax/robot.vim
RUN cp /home/MyUser/vim-rf/robot-ftdetect.vim /home/MyUser/.vim/ftdetect/robot.vim

# RUN chmod 755 /home/MyUser

WORKDIR /home/MyUser/vim-rf
USER MyUser
