# /* vim: set filetype=dockerfile : */

FROM vimrobotframework/vim_base:latest
MAINTAINER Samuel Branisa <branisa.samuel@icloud.com>

RUN mkdir -p ${USER_HOME}/.vim/pack/plugins/start

RUN git clone --depth 1 https://github.com/dense-analysis/ale.git /home/MyUser/.vim/pack/plugins/start/ale

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install robotframework-lint

RUN mkdir /home/MyUser/.vim/syntax
RUN mkdir /home/MyUser/.vim/ftdetect
COPY ./vim/robot-syntax.vim /home/MyUser/.vim/syntax/robot.vim
COPY ./vim/robot-ftdetect.vim /home/MyUser/.vim/ftdetect/robot.vim

COPY ./vim/vimrc-ale /home/MyUser/.vimrc
COPY ./robot /home/MyUser/vim-ale
COPY ./vim/rflint.vim /home/MyUser/.vim/pack/plugins/start/ale/ale_linters/robot/rflint.vim

WORKDIR /home/MyUser/vim-ale
USER MyUser
