name: vim_robotframework

on:
  push:
    branches: [ master ]
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: vimrobotframework/vim_base_syntax_test:latest
          shell: bash
          options: -v ${{ github.workspace }}:/github
          run: |
            set -e
            cp -r /github/syntax .vim/syntax
            cp -r /github/ftdetect .vim/ftdetect
            cp -r /github/other/test test
            mkdir -p .vim/pack/plugins/start/vim_rf/plugin
            cp /github/code/plugin .vim/pack/plugins/start/vim_robotframework/plugin
            TESTOUTPUT=$(testing.vim/tvim test plugin/robot_test.vim)
            echo "-----Testing vim-----"
            echo "$TESTOUTPUT"
            OUTPUTLINES=$(echo "$TESTOUTPUT" | wc -l)
            if [ "$OUTPUTLINES" -ne "1" ]; then
              exit 1
            fi
            echo "--------Vader--------"
            vim -c 'Vader! test/*.vader'

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
      - name: Kaniko build base Vim
        uses: aevea/action-kaniko@master
        with:
          image: vimrobotframework/vim_robotframework
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ steps.tagName.outputs.tag }}
          build_file: Dockerfile-vim-robotframework
          cache: true
          cache_registry: vimrobotframework/vim_robotframework_cache
