name: vim_robotframework

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kaniko build base Vim
        run: echo Test
        # uses: aevea/action-kaniko@master
        # with:
        #   image: vimrobotframework/vim_base
        #   username: ${{ secrets.DOCKERHUB_USERNAME }}
        #   password: ${{ secrets.DOCKERHUB_PASSWORD }}
        #   build_file: code/docker/Dockerfile-vim-base
        #   cache: true
        #   cache_registry: vimrobotframework/vim_base_cache
