name: vim_robotframework

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          image: vimrobotframework/vim_base_syntax_test:latest
          run: |
            ls -la
            echo "test123"
  #   test:
  #     runs-on: ubuntu-latest
  #     container:
  #       image: vimrobotframework/vim_base_syntax_test:latest
  #     steps:
  #       - name: Test
  #         run: |
  #           ls -la
  #           echo "test123"
  #           pwd
# build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Kaniko build base Vim
  #       run: echo Test
  #       # uses: aevea/action-kaniko@master
  #       # with:
  #       #   image: vimrobotframework/vim_base
  #       #   username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       #   password: ${{ secrets.DOCKERHUB_PASSWORD }}
  #       #   build_file: code/docker/Dockerfile-vim-base
  #       #   cache: true
  #       #   cache_registry: vimrobotframework/vim_base_cache
