name: vim_base_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build base Vim
        uses: aevea/action-kaniko@master
        with:
          image: vimrobotframework/vim_base
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          build_file: code/docker/Dockerfile-vim-base
          cache: true
          cache_registry: vimrobotframework/vim_base_cache
