name: vim_robotframework

on:
  push:
    branches: [ master ]
    tags:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: vimrobotframework/vim_base_syntax_test:latest
          shell: bash
          options: -v ${{ github.workspace }}:/github
          run: |
            set -e
            cp /github/code/vim/robot-syntax.vim .vim/syntax/robot.vim
            cp /github/code/vim/robot-ftdetect.vim .vim/ftdetect/robot.vim
            cp -r /github/code/test test
            mkdir -p .vim/pack/plugins/start/vim_robotframework/plugin
            cp /github/code/vim/list_tests.py .vim/pack/plugins/start/vim_robotframework/plugin/list_tests.py
            cp /github/code/vim/robot-commands.vim .vim/pack/plugins/start/vim_robotframework/plugin/robot-commands.vim
            TESTOUTPUT=$(testing.vim/tvim test plugin/robot_test.vim)
            echo "-----Testing vim-----"
            echo "$TESTOUTPUT"
            OUTPUTLINES=$(echo "$TESTOUTPUT" | wc -l)
            if [ "$OUTPUTLINES" -ne "1" ]; then
              exit 1
            fi
            echo "--------Vader--------"
            vim -c 'Vader! test/*.vader'
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kaniko build base Vim
        uses: aevea/action-kaniko@master
        with:
          image: vimrobotframework/vim_robotframework
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ GITHUB_REF/refs\/tags\// || 'latest' }}
          build_file: code/docker/Dockerfile-vim-robotframework
          cache: true
          cache_registry: vimrobotframework/vim_robotframework_cache
